UniversityCourseAndResultManagementSystem/UniversityCourseAndResultManagementSystem/Models/StudentResult.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityCourseAndResultManagementSystem.Models
{
    public class StudentResult
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please select a student Registration No!")]
        [DisplayName("Student Reg. No.")]
        public int StudentId { get; set; }

        public string Name { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }

        public int CourseId { get; set; }

        public string Grade { get; set; }
        public bool Status { get; set; }
    }
}

UniversityCourseAndResultManagementSystem/UniversityCourseAndResultManagementSystem/Models/StudentResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityCourseAndResultManagementSystem.Models
{
    public class StudentResultViewModel
    {
        public int StudentId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Grade { get; set; }

    }
}

UniversityCourseAndResultManagementSystem/UniversityCourseAndResultManagementSystem/Controllers/StudentResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementSystem.Manager;
using UniversityCourseAndResultManagementSystem.Models;

namespace UniversityCourseAndResultManagementSystem.Controllers
{
    public class StudentResultController : Controller
    {
        StudentManager studentManager = new StudentManager();
        CourseManager courseManager = new CourseManager();

        // GET: /StudentResult/Create
        public ActionResult Save()
        {
            IEnumerable<Student> students = studentManager.GetAllStudents();
            IEnumerable<Course> courses = courseManager.GetAllCourses();
            ViewBag.Students = students;
            ViewBag.Courses = courses;
            return View();
        }

        //
        // POST: /StudentResult/Create
        [HttpPost]
        public ActionResult Save(StudentResult studentResult)
        {
            try
            {
                ViewBag.Message = studentManager.Save(studentResult);
                IEnumerable<Student> students = studentManager.GetAllStudents();
                IEnumerable<Course> courses = courseManager.GetAllCourses();
                ViewBag.Students = students;
                ViewBag.Courses = courses;

                return View();
                //return RedirectToAction("Index");
            }
            catch (Exception exception)
            {
                ViewBag.Message = exception.InnerException.Message;
                return View();
            }
        }


        public JsonResult GetStudentById(int studentId)
        {
            StudentViewModel student = studentManager.GetStudentInformationById(studentId);
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCoursesTakebByStudent(int studentId)
        {
            IEnumerable<Course> courses = courseManager.GetCoursesTakenByaStudentById(studentId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult ViewStudentResult()
        {
            IEnumerable<Student> students = studentManager.GetAllStudents();
            ViewBag.Students = students;
            return View();
        }

        public JsonResult GetStudentResultByStudentId(int studentId)
        {
            IEnumerable<StudentResultViewModel> studentResults = studentManager.GetStudentResultByStudentId(studentId);
            return Json(studentResults, JsonRequestBehavior.AllowGet);
        }
	}
}

UniversityCourseAndResultManagementSystem/UniversityCourseAndResultManagementSystem/Views/StudentResult/Save.cshtml
@model UniversityCourseAndResultManagementSystem.Models.StudentResult
@{
    ViewBag.Title = "Add Student Result";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<hr />
<h2 class="slideshow" style="font-size: 30px; color: #5f223b">Save Student Result</h2>
<hr/>
@if (ViewBag.Message != null)
{
    <p style="font-size:30px;color:green">@ViewBag.Message</p>
}
<div>
    <form id="saveStudentResult" method="POST" class="alert-info">
       
        <div>
            <table class="table-striped">
                <tr>

                    <td>
                        @Html.LabelFor(s => s.StudentId)
                    </td>
                    <td>
                        <select id="StudentId" name="StudentId" class="form-control">
                            <option value="">--Select Reg. No.--</option>
                            @foreach (var student in ViewBag.Students)
                            {
                                <option value="@student.Id">@student.RegNo</option>
                            }
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="Name">Name</label>
                    </td>
                    <td>
                        <input type="text" id="Name" class="form-control" name="Name" readonly="readonly" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="Email">Email</label>
                    </td>
                    <td>
                        <input type="text" id="Email" class="form-control" name="Email" readonly="readonly" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="Department">Department</label>
                    </td>
                    <td>
                        <input type="text" id="Department" class="form-control" name="Department" readonly="readonly" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="CourseId">Course</label>
                    </td>
                    <td>
                        <select id="CourseId" name="CourseId" class="form-control">
                            <option value="">--Select Course--</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="Grade">Grade</label>
                    </td>
                    <td>
                        <select id="Grade" name="Grade" class="form-control">
                            <option value="">--Select Grade--</option>
                            <option value="A+">A+</option>
                            <option value="A">A</option>
                            <option value="A-">A-</option>
                            <option value="B+">B+</option>
                            <option value="B">B</option>
                            <option value="B-">B-</option>
                            <option value="C+">C+</option>
                            <option value="C">C</option>
                            <option value="C-">C-</option>
                            <option value="D+">D+</option>
                            <option value="D">D</option>
                            <option value="D-">D-</option>
                            <option value="F">F</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Save" class="btn btn-outline-primary" />
                    </td>
                </tr>
            </table>
        </div>
    </form>
</div>
@section scripts{
 
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {
            $("#saveStudentResult").validate({
                rules: {
                    StudentId: "required",
                    CourseId: "required",
                    Grade: "required"
                },
                messages: {
                    StudentId: "Please select the student reg no",
                    CourseId: "Please select a course",
                    Grade:"Please select a grade"
                }
            });




            $("#StudentId").change(function () {
                var stId = $("#StudentId").val();
                $("#CourseId").empty();
                $("#CourseId").append('<option value="">Select Course</option>');

                var json = { studentId: stId };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentById", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        //alert(data);

                        var name = data.Name;
                        var email = data.Email;
                        var dept = data.Department;
                        $("#Name").val(name);
                        $("#Email").val(email);
                        $("#Department").val(dept);
                    }
                });


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCoursesTakebByStudent", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {


                        $.each(data, function (key, value) {
                          
                            $("#CourseId").append('<option value=' + value.Id + '>' + value.Name + '</option>');

                        });
                    }
                });

            });

        });
    </script>
}

UniversityCourseAndResultManagementSystem/UniversityCourseAndResultManagementSystem/Views/StudentResult/ViewStudentResult.cshtml
@{
    ViewBag.Title = "Student Result";
 
}
<script language="javascript">


    function myPrint() {
        var myPrintContent = document.getElementById('printDIV');
        var myPrintWindow = window.open('width=400,height=400');
        myPrintWindow.document.write(myPrintContent.innerHTML);
        myPrintWindow.document.getElementById('hiddenDiv').style.display = 'block';
        myPrintWindow.document.close();
        myPrintWindow.focus();
        myPrintWindow.print(); 
        myPrintWindow.close();
        return false;
    }
</script>
<div>
    <form id="viewStudentResult" >
        <hr />
        <h2 style="font-size: 30px; color: #5f223b"> View Student Result</h2>
        <hr />
        <table class="table table-striped alert-info " style="width: 50%">
            <tr>
                <td>
                    <label for="StudentId"  >Student Reg. No.</label>
                </td>
                <td>
                    <select id="StudentId" name="StudentId" class="form-control">
                        <option value="">--Select Reg. No.--</option>
                        @foreach (var student in ViewBag.Students)
                        {
                            <option value="@student.Id">@student.RegNo</option>
                        }
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="Name">Name</label>
                </td>
                <td>
                    <input type="text" class="form-control" id="Name" name="Name" readonly="readonly" @*placeholder="Please select the Student Reg No"*@ />
                </td>
            </tr>
            <tr>
                <td>
                    <label for="Email">Email</label>
                </td>
                <td>
                    <input type="text" class="form-control" id="Email" name="Email" readonly="readonly" />
                </td>
            </tr>
            <tr>
                <td>
                    <label for="Department">Department</label>
                </td>
                <td>
                    <input type="text" class="form-control" id="Department" name="Department" readonly="readonly" />
                </td>
            </tr>
            <tr>
                <td></td>
                <td>

                    <input type="submit" class="btn-outline-primary" value="Make PDF" onclick="myPrint();" />
                </td>
            </tr>
        </table>
        <div id="studenRsult">
            <div id="printDIV">
                <div id="hiddenDiv" align="center" style="display: none">
                   
                    <h3 style="text-align: center; padding: 5px 10px; color: blueviolet; border-radius: 10px;"><b><u>Result</u></b></h3>
                    <table style="width: 100%">
                        <tr>
                            <td width="30%" style="text-align: right;">Name: </td>
                            <td width="70%"><label id="printName" style="font-weight: bold;"></label></td>
                        </tr>
                        <tr>
                            <td style="text-align: right;">Email: </td>
                            <td><label id="printEmail"></label></td>
                        </tr>
                        <tr>
                            <td style="text-align: right;">Department: </td>
                            <td><label id="printDepartment"></label></td>
                        </tr>
                    </table>
                    <br/>
                    <br/>
                    <table class="table table-bordered alert-info" style="border: 1px solid black; width: 100%; border-collapse: collapse; margin-bottom: 100px;">
                        <tr>
                            <th style="border: 1px solid black; ">Code</th>
                            <th style="border: 1px solid black; ">Name</th>
                            <th style="border: 1px solid black; ">Grade</th>
                        </tr>
                        <tbody id="resultPrintData" style="text-align: center;"></tbody>
                    </table>
                    <br/>
                    <br/>
                    <table width="100%">
                        <tr>
                            <td>
                                <p style="text-align: left; font-size: 10px;">Publication Date and time: @DateTime.Now</p>
                            </td>
                            
                        </tr>
                    </table>
                </div>
            </div>
            <br/>
            <hr/>
            <table class="table table-bordered table-hover alert-dark" style="border: 1px solid black; width: 100%; border-collapse: collapse;">
                <caption style="font-size: 30px; font-weight: bolder; margin-bottom: 20px">@*Result*@</caption>
                <tr  style="text-align: center">
                    <th>Code</th>
                    <th>Name</th>
                    <th>Grade</th>
                </tr>
                <tbody id="resultData" class="alert-warning hover " style="text-align: center"></tbody>
            </table>
        </div>
    </form>
</div>
@section scripts{
    
<script src="~/Scripts/jquery-3.3.1.js"></script>
    <script>
        $(document).ready(function() {
            $("#StudentId").change(function () {
                var stId = $("#StudentId").val();

                $("#resultData").empty();
                var json = { studentId: stId };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentById", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                      

                        var name = data.Name;
                        var email = data.Email;
                        var dept = data.Department;
                        $("#Name").val(name);
                        $("#Email").val(email);
                        $("#Department").val(dept);
                        $("#printName").text(name);
                        $("#printEmail").text(email);
                        $("#printDepartment").text(dept);

                    }
                });


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentResultByStudentId", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {

                        var i = 0;

                        $.each(data, function (index, value) {

                            var row = $("<tr><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Code + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Name + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Grade + "</td></tr>");
                            $("#resultData").append(row);
                            var row2 = $("<tr><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Code + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Name + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Grade + "</td></tr>");
                            $("#resultPrintData").append(row2);

                        });
                    }
                });

            });

        });
    </script>
}