UniversityCourseAndResultManagementSystem/UniversityCourseAndResultManagementSystem/Controllers/ViewCourseStaticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementSystem.Manager;
using UniversityCourseAndResultManagementSystem.Models;

namespace UniversityCourseAndResultManagementSystem.Controllers
{
    public class ViewCourseStaticsController : Controller
    {
        DepartmentManager departmentManager = new DepartmentManager();
        CourseManager courseManager = new CourseManager();

        //
        // GET: /ViewCourseStatics/

        public ActionResult ShowCourseStatics()
        {
            IEnumerable<Department> departments = departmentManager.GetAllDepts();
            ViewBag.Departments = departments;
            List<CourseViewModel> courseViewModels = courseManager.GetCourseViewModels();
            return View(courseViewModels);
        }

        public JsonResult GetCourseInformationByDepartmentId(int departmentId)
        {
            IEnumerable<CourseViewModel> courseViewModels = courseManager.GetCourseViewModels().FindAll(deptId => deptId.DepartmentId == departmentId);
           
            return Json(courseViewModels, JsonRequestBehavior.AllowGet);


        }
	}
}

UniversityCourseAndResultManagementSystem/UniversityCourseAndResultManagementSystem/Views/ViewCourseStatics/ShowCourseStatics.cshtml
@model IEnumerable<UniversityCourseAndResultManagementSystem.Models.CourseViewModel>
@{
    ViewBag.Title = "Show Course Statics";
}
<hr />
<h2 style="font-size: 30px; color: #5f223b">View Course Statics</h2>
<hr />
<div class="form-group">
    <label for="DepartmentId" class="font-weight-bold shadow-sm btn-outline-primary">Select Department</label>
    <select id="DepartmentId" name="DepartmentId" class="form-control">
        <option value="">Select Department....</option>
        @foreach (var dept in ViewBag.Departments)
{
    <option value="@dept.DepartmentId">@dept.Name</option>
}
    </select>
</div>
<table class="table table-striped table-bordered table-hover" style="text-align: center;">
    <tr class="active">
        <th class="alert-info">Code</th>
        <th class="alert-info">Name</th>
        <th class="alert-info">Semester</th>
        <th class="alert-info">Teacher</th>
    </tr>
    <tbody id="myData"></tbody>
</table>
@section scripts{
    
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#DepartmentId").change(function () {
                $("#myData").empty();
                var deptId = $("#DepartmentId").val();
                var json = { departmentId: deptId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseInformationByDepartmentId", "ViewCourseStatics")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {

                        $.each(data, function (index, value) {

                            var row = $("<tr><td>" + value.Code + "</td><td>" + value.Name + "</td><td>" + value.Semester + "</td><td>" + value.Teacher + "</td></tr>");
                            $("#myData").append(row);
                        });
                    }
                });
            });
        });
    </script>
    <script src="~/Scripts/jquery-2.2.0.js"></script>

    @*<script src="~/Scripts/bootstrap.js"></script>*@
    <script>
        $('.dropdown').hover(function () {
            $('.dropdown-toggle', this).trigger('click');
        });
    </script>
}