UniversityCourseAndResultManagementSystem/UniversityCourseAndResultManagementSystem/Controllers/EnrollStuInACouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementSystem.Manager;
using UniversityCourseAndResultManagementSystem.Models;

namespace UniversityCourseAndResultManagementSystem.Controllers
{
    public class EnrollStuInACouseController : Controller
    {
        StudentManager studentManager = new StudentManager();
        CourseManager courseManager = new CourseManager();

        [HttpGet]
        public ActionResult Enroll()
        {
            IEnumerable<Student> students = studentManager.GetAllStudents();
            IEnumerable<Course> courses = courseManager.GetAllCourses();
            ViewBag.Students = students;
            ViewBag.Courses = courses;
            return View();
        }
        [HttpPost]
        public ActionResult Enroll(EnrollStudentInCourse enrollStudent)
        {
            string message;
           
                message = studentManager.Save(enrollStudent);
                ViewBag.Message = message;
                IEnumerable<Student> students = studentManager.GetAllStudents();
                IEnumerable<Course> courses = courseManager.GetAllCourses();
                ViewBag.Students = students;
                ViewBag.Courses = courses;

                return View();
          
        }

        public JsonResult GetStudentById(int studentId)
        {
            StudentViewModel student = studentManager.GetStudentInformationById(studentId);
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseByStudentId(int studentId)
        {
            Student aStudent = studentManager.GetAllStudents().Find(st => st.Id == studentId);
            IEnumerable<Course> courses = courseManager.GetAllCourses().FindAll(d => d.DepartmentId == aStudent.DepartmentId);
            return Json(courses, JsonRequestBehavior.AllowGet);

        }
	}
}

UniversityCourseAndResultManagementSystem/UniversityCourseAndResultManagementSystem/Views/EnrollStuInACouse/Enroll.cshtml
@{
    ViewBag.Title = "Enroll Student In a Course";

}
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<div>
    <hr />
    <h2 class="slideshow" style="font-size: 30px; color: #5f223b">Enroll In a Course</h2>
    <hr />
 
    @if (ViewBag.Message != null && ViewBag.Message == "Saved Successfully")
    {
    <p style="font-size: 30px; color: green">@ViewBag.Message</p>
    }
    else
    {
    <p style="font-size: 30px; color: red">@ViewBag.Message</p>
    }

    <form id="enrollCourse" method="POST" class="alert-info">
        <div class="form-group alert-dark" style="width: 35%;">
            <label for="StudentId">Registration No</label>
            <select id="StudentId" name="StudentId" class="form-control">
                <option value="">--Select Reg. No.--</option>
                @foreach (var student in ViewBag.Students)
                {
                    <option value="@student.Id">@student.RegNo</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="Name">Name</label>
            <input type="text" class="form-control" id="Name" readonly="readonly" name="Name" placeholder="Read Only">
        </div>
        <div class="form-group alert-dark" style="width: 35%;">
            <label for="Email">Email</label>
            <input type="text" class="form-control" id="Email" readonly="readonly" name="Email" placeholder="Read Only">
        </div>
        <div class="form-group">
            <label for="DepartmentId">Department</label>
            <input type="text" class="form-control" id="DepartmentId" name="DepartmentId" readonly="readonly" placeholder="Read Only" />
        </div>
        <div class="form-group alert-dark" style="width: 35%;">
            <label for="CourseId">Course</label>
            <select id="CourseId" name="CourseId" class="form-control">
                <option value="">--Select Course--</option>
            </select>
        </div>
        <div class="form-group">
            <label for="EnrollDate">Date</label>
            <input type="text" class="form-control" id="EnrollDate" name="EnrollDate" value="@DateTime.Now.ToShortDateString()">
        </div>

        <button type="submit" class="btn btn-outline-primary form-group " >Enroll</button>
    </form>
</div>
@section scripts{



    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            $('#EnrollDate').datepicker();
            $("#enrollCourse").validate({
                rules: {
                    StudentId: "required",
                    CourseId: "required",
                    EnrollDate: "required"
                },
                messages: {
                    StudentId: "Please select a student Registration No",
                    CourseId: "Please select a Course",
                    EnrollDate: "Select date"
                }
            });

            $("#StudentId").change(function () {
                var stId = $("#StudentId").val();
                $("#CourseId").empty();
                $("#CourseId").append('<option value=' + "" + '>--Select Course--</option>');

                var json = { studentId: stId };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentById", "EnrollStuInACouse")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        //alert(data);

                        var name = data.Name;
                        var email = data.Email;
                        var dept = data.Department;
                        $("#Name").val(name);
                        $("#Email").val(email);
                        $("#DepartmentId").val(dept);
                    }
                });


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByStudentId", "EnrollStuInACouse")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {


                        $.each(data, function (key, value) {
                          
                            $("#CourseId").append('<option value=' + value.Id + '>' + value.Name + '</option>');

                        });
                    }
                });

            });
        });
    </script>


}